### ISSUE TITLE
Provide instructions on how to setup on linux

### ISSUE THREAD

**Issue by genga898** [namigop/FintX#11]
Kindly provide instructions on how to set up the tool on Linux distributions.

**Comment by namigop** [comment]
@genga898 I've updated [v1.0 release with the linux build](https://github.com/namigop/FintX/releases/tag/rel-v1.0 ). Can you please try it out?  Just extract the zip file to any folder on you linux machine and then run the FintX executable

**Comment by genga898** [comment]
@namigop Thank you, it works now. Appreciate the fast response.
