### ISSUE TITLE
Compilation error for Tefin.Grpc project

### ISSUE THREAD

**Issue by ClassyCircuit** [namigop/FintX#12]
How to reproduce:

1) Clone main branch
2) Run "dotnet build .\Tefin.sln"

Error: C:\Users\abc\.nuget\packages\grpc.tools\2.58.0\build\_protobuf\Google.Protobuf.Tools.targets(52,5): error : Google.Protobuf.Tools proto compilation is only supported by default in a C# project (extension .csproj) [C:Users\abc\source\repos\learn\FintX\source\Tefin.Grpc\Tefin.Grpc.fsproj]

Can you please provide instructions what needs to be done so Tefin.Grpc project compiles?
I have tried looking online for a solution, but couldn't find one.

I am using .NET 8 SDK, Visual Studio 2022.

**Comment by ClassyCircuit** [comment]
Yes that works.
I suggest you add this line:
`<Protobuf_ProjectSupported>true</Protobuf_ProjectSupported>`
to Tefin.Grpc.fsproj.

Then compilation will work out of the box with no extra parameters.

**Comment by namigop** [comment]
You're right. Thanks!
